version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus-config/prometheus.yaml:/etc/prometheus/prometheus.yml
    restart: always
    ports:
      - 9090:9090

  grafana:
    build:
      context: .
      dockerfile: cusgrafana.dockerfile
    restart: always
    ports:
      - 3000:3000
